config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :links do
  	member do
  		put "Like", to: 'links#upvote'
  		put "Dislike", to: 'links#downvote'
  	end
  end


  root to: 'links#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
	validates :title, presence: true, length: { minimum: 3}
	validates :url, presence: true


	acts_as_votable
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @link = Link.find(params[:id])
    @link.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @link = Link.find(params[:id])
    @link.downvote_by current_user
    redirect_to :back
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyReddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Arvo" rel="stylesheet">
    <style>
      body{
        font-family: 'Arvo', serif;
      }
    </style>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'MyReddit', links_path, class: 'navbar-brand' %>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
              <li><%= link_to 'New Article', new_link_path %></li>
              <li><%= link_to 'Account', edit_user_registration_path %></li>
              <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <% else %>
              <li><%= link_to 'Sign In', new_user_session_path %></li>
              <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="container">
    
    <% flash.each do |name, msg| %>
      <div  class = "alert alert-warning">
        <%= msg %>
      </div>
    <% end %>
    
      <%= yield %>
    </div>
  </body>
</html>

app/views/links/_form.html.erb
<div class="col-md-6">
<%= form_for(link) do |f| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_area :url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>
</div>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
  <p class="alert alert-warning"><%= notice %></p>

<h1 class="text-center">All Articles</h1>

    <% @links.each do |link| %>
    <div class="row">
      <div class="panel panel-info col-md-9">
          <h3><%= link_to link.title.capitalize, link_path(link) %></h3>
        <div class="panel-body"><%= link.url %><br>
        <div class="small"><%= time_ago_in_words(link.created_at) %> ago</div>
        <br>
        <%= link_to Like_link_url(link), method: :put, class: 'btn btn-primary' do %>
          <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
          Like
          <%= link.get_upvotes.size %>
        <% end %>
        <%= link_to Dislike_link_url(link), method: :put, class: 'btn btn-danger' do %>
          <i class="fa fa-thumbs-o-down" aria-hidden="true"></i>
          Dislike
          <%= link.get_downvotes.size %>
        <% end %>
        <div class="btn btn-default"><%= link_to 'Show', link %></div>
        <% if link.user == current_user %>
          <div class="btn btn-default"><%= link_to 'Edit', edit_link_path(link) %></div>
          <div class="btn btn-default"><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></div>
        <% end %>
        </div>
      </div>
    </div>
    <% end %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path, class: 'btn btn-default' %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @link.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @link.url %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>